export const pages= [{name: 'Home', path: '/'}, {name: 'About', path: '/about'}, {name: 'Contact', path: '/contact'}];

export const Catagory= [
    {name: 'All', image: '/menu_8.png'},
    {name: 'Pizza', image: '/menu_1.png'},
    {name: 'Burger', image: '/menu_2.png'}, 
    {name: 'Sushi', image: '/menu_3.png'},
    {name: 'Dessert', image: '/menu_4.png'},
    {name: 'Drink', image: '/menu_5.png'},
    {name: 'Salad', image: '/menu_6.png'},
    {name: 'Seafood', image: '/menu_7.png'},
    {name: 'Pasta', image: '/menu_8.png'},
    
]

export const MenuItems= [
    {name: 'Pizza', image: '/food_1.png', price: 10.99,cata: 'Pizza', id: 1},
    {name: 'Burger', image: '/food_2.png', price: 8.99,cata: 'Burger' , id: 2},
    {name: 'Sushi', image: '/food_3.png', price: 12.99,cata: 'Sushi' , id: 3},
    {name: 'Dessert', image: '/food_4.png', price: 5.99,cata: 'Dessert' , id: 4},
    {name: 'Drink', image: '/food_5.png', price: 3.99,cata: 'Drink' , id: 5},
    {name: 'Salad', image: '/food_6.png', price: 7.99,cata: 'Salad' , id: 6},
    {name: 'Seafood', image: '/food_7.png', price: 15.99,cata: 'Seafood' , id: 7},
    {name: 'Pasta', image: '/food_8.png', price: 9.99,cata: 'Pasta' , id: 8},
    {name: 'Pizza', image: '/food_9.png', price: 10.99,cata: 'Pizza' , id: 9},
    {name: 'Burger', image: '/food_12.png', price: 8.99,cata: 'Burger' , id: 10},
    {name: 'Sushi', image: '/food_13.png', price: 12.99,cata: 'Sushi' , id: 11},
    {name: 'Pizza', image: '/food_1.png', price: 10.99,cata: 'Pizza' , id: 12},
    {name: 'Burger', image: '/food_2.png', price: 8.99,cata: 'Burger' , id: 13},
    {name: 'Sushi', image: '/food_3.png', price: 12.99,cata: 'Sushi' , id: 14},
    {name: 'Dessert', image: '/food_4.png', price: 5.99,cata: 'Dessert' , id: 15},
    {name: 'Drink', image: '/food_5.png', price: 3.99,cata: 'Drink' , id: 16},
    {name: 'Salad', image: '/food_6.png', price: 7.99,cata: 'Salad' , id: 17},
    {name: 'Seafood', image: '/food_7.png', price: 15.99,cata: 'Seafood' , id: 18},
    {name: 'Pasta', image: '/food_8.png', price: 9.99,cata: 'Pasta' , id: 19},
    {name: 'Pizza', image: '/food_9.png', price: 10.99,cata: 'Pizza' , id: 20},
    {name: 'Burger', image: '/food_12.png', price: 8.99,cata: 'Burger' , id: 21},
    {name: 'Sushi', image: '/food_13.png', price: 12.99,cata: 'Sushi' , id: 22},
    {name: 'Dessert', image: '/food_14.png', price: 5.99,cata: 'Dessert' , id: 23},
    {name: 'Drink', image: '/food_15.png', price: 3.99,cata: 'Drink' , id: 24},
    {name: 'Salad', image: '/food_16.png', price: 7.99,cata: 'Salad' , id: 25},
    {name: 'Seafood', image: '/food_17.png', price: 15.99,cata: 'Seafood' , id: 26},
    {name: 'Pasta', image: '/food_18.png', price: 9.99,cata: 'Pasta' , id: 27},
    {name: 'Pizza', image: '/food_10.png', price: 10.99,cata: 'Pizza' , id: 28},
    {name: 'Burger', image: '/food_22.png', price: 8.99,cata: 'Burger' , id: 29},
    {name: 'Sushi', image: '/food_25.png', price: 12.99,cata: 'Sushi' , id: 30},
    {name: 'Dessert', image: '/food_29.png', price: 5.99,cata: 'Dessert' , id: 31},
    {name: 'Drink', image: '/food_27.png', price: 3.99,cata: 'Drink' , id: 32},
    {name: 'Salad', image: '/food_30.png', price: 7.99,cata: 'Salad' , id: 33},
    {name: 'Seafood', image: '/food_11.png', price: 15.99,cata: 'Seafood' , id: 34},
    {name: 'Pasta', image: '/food_22.png', price: 9.99,cata: 'Pasta' , id: 35},
    {name: 'Pizza', image: '/food_13.png', price: 10.99,cata: 'Pizza' , id: 36},
    {name: 'Burger', image: '/food_14.png', price: 8.99,cata: 'Burger' , id: 37},
    {name: 'Sushi', image: '/food_15.png', price: 12.99,cata: 'Sushi' , id: 38},
    {name: 'Dessert', image: '/food_16.png', price: 5.99,cata: 'Dessert' , id: 39},

]