export const pages= [{name: 'Home', path: '/'}, {name: 'About', path: '/about'}, {name: 'Contact', path: '/contact'}];

export const Catagory= [
    {name: 'All', image: '/menu_8.png'},
    {name: 'Pizza', image: '/menu_1.png'},
    {name: 'Burger', image: '/menu_2.png'}, 
    {name: 'Sushi', image: '/menu_3.png'},
    {name: 'Dessert', image: '/menu_4.png'},
    {name: 'Drink', image: '/menu_5.png'},
    {name: 'Salad', image: '/menu_6.png'},
    {name: 'Seafood', image: '/menu_7.png'},
    {name: 'Pasta', image: '/menu_8.png'},
    
]

export const MenuItems= [
    {name: 'Pizza', image: '/food_1.png', price: 10.99,cata: 'Pizza'},
    {name: 'Burger', image: '/food_2.png', price: 8.99,cata: 'Burger'},
    {name: 'Sushi', image: '/food_3.png', price: 12.99,cata: 'Sushi'},
    {name: 'Dessert', image: '/food_4.png', price: 5.99,cata: 'Dessert'},
    {name: 'Drink', image: '/food_5.png', price: 3.99,cata: 'Drink'},
    {name: 'Salad', image: '/food_6.png', price: 7.99,cata: 'Salad'},
    {name: 'Seafood', image: '/food_7.png', price: 15.99,cata: 'Seafood'},
    {name: 'Pasta', image: '/food_8.png', price: 9.99,cata: 'Pasta'},
    {name: 'Pizza', image: '/food_9.png', price: 10.99,cata: 'Pizza'},
    {name: 'Burger', image: '/food_12.png', price: 8.99,cata: 'Burger'},
    {name: 'Sushi', image: '/food_13.png', price: 12.99,cata: 'Sushi'},
    {name: 'Pizza', image: '/food_1.png', price: 10.99,cata: 'Pizza'},
    {name: 'Burger', image: '/food_2.png', price: 8.99,cata: 'Burger'},
    {name: 'Sushi', image: '/food_3.png', price: 12.99,cata: 'Sushi'},
    {name: 'Dessert', image: '/food_4.png', price: 5.99,cata: 'Dessert'},
    {name: 'Drink', image: '/food_5.png', price: 3.99,cata: 'Drink'},
    {name: 'Salad', image: '/food_6.png', price: 7.99,cata: 'Salad'},
    {name: 'Seafood', image: '/food_7.png', price: 15.99,cata: 'Seafood'},
    {name: 'Pasta', image: '/food_8.png', price: 9.99,cata: 'Pasta'},
    {name: 'Pizza', image: '/food_9.png', price: 10.99,cata: 'Pizza'},
    {name: 'Burger', image: '/food_12.png', price: 8.99,cata: 'Burger'},
    {name: 'Sushi', image: '/food_13.png', price: 12.99,cata: 'Sushi'},
    {name: 'Dessert', image: '/food_14.png', price: 5.99,cata: 'Dessert'},
    {name: 'Drink', image: '/food_15.png', price: 3.99,cata: 'Drink'},
    {name: 'Salad', image: '/food_16.png', price: 7.99,cata: 'Salad'},
    {name: 'Seafood', image: '/food_17.png', price: 15.99,cata: 'Seafood'},
    {name: 'Pasta', image: '/food_18.png', price: 9.99,cata: 'Pasta'},
    {name: 'Pizza', image: '/food_10.png', price: 10.99,cata: 'Pizza'},
    {name: 'Burger', image: '/food_22.png', price: 8.99,cata: 'Burger'},
    {name: 'Sushi', image: '/food_25.png', price: 12.99,cata: 'Sushi'},
    {name: 'Dessert', image: '/food_29.png', price: 5.99,cata: 'Dessert'},
    {name: 'Drink', image: '/food_27.png', price: 3.99,cata: 'Drink'},
    {name: 'Salad', image: '/food_30.png', price: 7.99,cata: 'Salad'},
    {name: 'Seafood', image: '/food_11.png', price: 15.99,cata: 'Seafood'},
    {name: 'Pasta', image: '/food_22.png', price: 9.99,cata: 'Pasta'},
    {name: 'Pizza', image: '/food_13.png', price: 10.99,cata: 'Pizza'},
    {name: 'Burger', image: '/food_14.png', price: 8.99,cata: 'Burger'},
    {name: 'Sushi', image: '/food_15.png', price: 12.99,cata: 'Sushi'},
    {name: 'Dessert', image: '/food_16.png', price: 5.99,cata: 'Dessert'},

]